name: mc-alg
version: '${version}'
main: ren.lawliet.mc.mcalg.Mc_alg
api-version: '1.20'
commands:
  alg:
    description: "Mc Alg"
    usage: /alg
    permission-message: "permission denied"
    permission: "alg.use"